
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  port: 5432
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tblog_development

  
test:
  <<: *default
  database: tblog_test


production:
  <<: *default
  database: tblog_production
  username: tblog
  password: <%= ENV['TBLOG_DATABASE_PASSWORD'] %>
